CREATE DATABASE puzzlegame;
USE puzzlegame;

CREATE TABLE `puzzle`
(
id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(60) NOT NULL UNIQUE
) ENGINE=InnoDB CHARACTER SET=utf8;

CREATE TABLE `image`
(
id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(60) NOT NULL UNIQUE,
url VARCHAR(255) NOT NULL
) ENGINE=InnoDB CHARACTER SET=utf8;

CREATE TABLE `puzzleImage`
(
id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
idPuzzle INT UNSIGNED NOT NULL,
idImage INT UNSIGNED NOT NULL,
INDEX(idPuzzle),
INDEX(idImage),
FOREIGN KEY(idPuzzle) REFERENCES `puzzle`(id) ON DELETE NO ACTION ON UPDATE NO ACTION,
FOREIGN KEY(idImage) REFERENCES `image`(id) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB;